### ISSUE TITLE
Support Open RIA Services

### ISSUE THREAD

**Issue by icnocop** [autofac/Autofac.Extras.DomainServices#1]
Hi.

Thank you for Autofac.Extras.DomainServices.

I would like to request support for Open RIA Services.
https://openriaservices.codeplex.com/

It's the successor of WCF RIA Services.

Thank you.

**Comment by tillig** [comment]
I'm going to be honest - I'm not sure if this is going to happen given the current number of integrations we have to support and the fact that most of those have much higher user bases. With Autofac 4 we were actually planning on deprecating support for this package entirely - it would live on, untouched, and we'd just maintain compatibility with core Autofac as it progressed... and eventually not even that.

Especially as we move into DNX and ASP.NET 5 territory, where there are even more integration points we need to build for and test, I don't know that switching this up, testing, updating the doc, etc. is really in the cards.

However, if you're interested in implementing this yourself, we welcome pull requests... and if you want to take an even more active stance, I'd be happy to let you own this. Alternatively, it's MIT code - you can fork it and create your own integration package for Open RIA Services and own the whole thing directly.

I'll leave this open in case someone wants to take it on, but... I just wouldn't hold my breath for it. :)

**Comment by tillig** [comment]
As of the release of Autofac 4, this library is in maintenance mode so no enhancements will be made.

If you would like to take ownership of this particular integration long term, let us know.

Given we won't be doing the enhancement, I'm going to close the issue.
